inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.2

Metrics/MethodLength:
  Max: 12

Metrics/LineLength:
  Max: 120

ClassLength:
  Max: 180

Metrics/ModuleLength:
  Exclude:
  - 'spec/**/*'
  - 'test/**/*'

Metrics/BlockLength:
  Exclude:
  - 'spec/**/*'
  - 'test/**/*'
  - '*.gemspec'

Style/Documentation:
  Exclude:
  - 'spec/**/*'
  - 'test/**/*'
  - 'lib/occi/api/version.rb'

Style/CommentedKeyword:
  Exclude:
  - 'examples/*'
